export const MODAL_NAMESPACE = {
  EVENT_CREATE: 'EVENT_CREATE_MODAL',
  EVENT_QR_CODE: 'EVENT_QR_CODE_MODAL',
  EVENT_DETAIL: 'EVENT_DETAIL_MODAL',
  EVENT_SCANNER: 'EVENT_SCANNER_MODAL',
  EVENT_PARTICIPANTS: 'EVENT_PARTICIPANTS_MODAL'
} as const;

export type AppModalName =
  (typeof MODAL_NAMESPACE)[keyof typeof MODAL_NAMESPACE];
